"""Display identities are separate from the legal 13F reporting managers."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HoldingsSubject:
    id: str
    title: str
    kind: str
    filer_cik: int
    filer_name: str
    attribution: str


SUBJECTS = (
    HoldingsSubject("michael-burry", "Michael Burry", "celebrity", 1649339,
                    "Scion Asset Management, LLC", "Scion 13F; not a personal trade ledger"),
    HoldingsSubject("warren-buffett", "Warren Buffett", "celebrity", 1067983,
                    "BERKSHIRE HATHAWAY INC", "Berkshire 13F; not solely Buffett's decisions"),
    HoldingsSubject("bill-ackman", "Bill Ackman", "celebrity", 2026053,
                    "PERSHING SQUARE INC.", "Pershing Square Inc. 13F; not a personal trade ledger"),
    HoldingsSubject("cathie-wood", "Cathie Wood", "celebrity", 1697748,
                    "ARK Investment Management LLC", "ARK Investment Management LLC 13F; not Wood's personal trades"),
    HoldingsSubject("david-tepper", "David Tepper", "celebrity", 1656456,
                    "Appaloosa LP", "Appaloosa LP 13F; not Tepper's personal trades"),
    HoldingsSubject("daniel-loeb", "Daniel Loeb", "celebrity", 1040273,
                    "Third Point LLC", "Third Point LLC 13F; not Loeb's personal trades"),
    HoldingsSubject("ken-griffin", "Ken Griffin", "celebrity", 1423053,
                    "CITADEL ADVISORS LLC", "Citadel Advisors LLC 13F; not Griffin's personal trades"),
    HoldingsSubject("chase-coleman", "Chase Coleman", "celebrity", 1167483,
                    "TIGER GLOBAL MANAGEMENT LLC", "Tiger Global Management LLC 13F; not Coleman's personal trades"),
    HoldingsSubject("philippe-laffont", "Philippe Laffont", "celebrity", 1135730,
                    "COATUE MANAGEMENT LLC", "Coatue Management LLC 13F; not Laffont's personal trades"),
    HoldingsSubject("stanley-druckenmiller", "Stanley Druckenmiller", "celebrity", 1536411,
                    "Duquesne Family Office LLC", "Duquesne Family Office LLC 13F; not a personal trade ledger"),
    HoldingsSubject("seth-klarman", "Seth Klarman", "celebrity", 1061768,
                    "BAUPOST GROUP LLC/MA", "Baupost Group LLC 13F; not Klarman's personal trades"),
    HoldingsSubject("david-einhorn", "David Einhorn", "celebrity", 1489933,
                    "DME Capital Management, LP", "DME Capital Management LP 13F; not Einhorn's personal trades"),
    HoldingsSubject("steve-cohen", "Steve Cohen", "celebrity", 1603466,
                    "Point72 Asset Management, L.P.", "Point72 Asset Management LP 13F; not Cohen's personal trades"),
    HoldingsSubject("ole-andreas-halvorsen", "Ole Andreas Halvorsen", "celebrity", 1103804,
                    "VIKING GLOBAL INVESTORS LP", "Viking Global Investors LP 13F; not a personal trade ledger"),
    HoldingsSubject("paul-singer", "Paul Singer", "celebrity", 1791786,
                    "Elliott Investment Management L.P.", "Elliott Investment Management LP 13F; not personal trades"),
    HoldingsSubject("li-lu", "Li Lu", "celebrity", 1709323,
                    "Himalaya Capital Management LLC", "Himalaya Capital Management LLC 13F; not personal trades"),
    HoldingsSubject("nelson-peltz", "Nelson Peltz", "celebrity", 1345471,
                    "TRIAN FUND MANAGEMENT, L.P.", "Trian Fund Management LP 13F; not personal trades"),
    HoldingsSubject("cliff-asness", "Cliff Asness", "celebrity", 1167557,
                    "AQR CAPITAL MANAGEMENT LLC", "AQR Capital Management LLC 13F; not personal trades"),
    HoldingsSubject("peter-thiel", "Peter Thiel", "celebrity", 1562087,
                    "Thiel Macro LLC", "Thiel Macro LLC 13F; not Thiel's personal trades or Founders Fund holdings"),
    HoldingsSubject("leopold-aschenbrenner", "Leopold Aschenbrenner", "celebrity", 2045724,
                    "Situational Awareness LP", "Situational Awareness LP 13F; not Aschenbrenner's personal trades or live holdings"),
    HoldingsSubject("duan-yongping", "Duan Yongping", "celebrity", 1759760,
                    "H&H International Investment, LLC", "H&H International Investment, LLC 13F; not Duan's complete personal portfolio or live holdings"),
    HoldingsSubject("bridgewater", "Bridgewater Associates", "institution", 1350694,
                    "Bridgewater Associates, LP", "Bridgewater Associates LP 13F"),
    HoldingsSubject("citadel", "Citadel Advisors", "institution", 1423053,
                    "CITADEL ADVISORS LLC", "Citadel Advisors LLC 13F"),
    HoldingsSubject("ark", "ARK Investment Management", "institution", 1697748,
                    "ARK Investment Management LLC", "ARK Investment Management LLC 13F"),
    HoldingsSubject("tiger-global", "Tiger Global Management", "institution", 1167483,
                    "TIGER GLOBAL MANAGEMENT LLC", "Tiger Global Management LLC 13F"),
    HoldingsSubject("renaissance", "Renaissance Technologies", "institution", 1037389,
                    "RENAISSANCE TECHNOLOGIES LLC", "Renaissance Technologies LLC 13F"),
    HoldingsSubject("coatue", "Coatue Management", "institution", 1135730,
                    "COATUE MANAGEMENT LLC", "Coatue Management LLC 13F"),
    HoldingsSubject("scion", "Scion Asset Management", "institution", 1649339,
                    "Scion Asset Management, LLC", "Scion Asset Management LLC 13F"),
    HoldingsSubject("berkshire", "Berkshire Hathaway", "institution", 1067983,
                    "BERKSHIRE HATHAWAY INC", "Berkshire Hathaway Inc. 13F"),
    HoldingsSubject("pershing-square", "Pershing Square", "institution", 2026053,
                    "PERSHING SQUARE INC.", "Pershing Square Inc. 13F"),
    HoldingsSubject("appaloosa", "Appaloosa", "institution", 1656456,
                    "Appaloosa LP", "Appaloosa LP 13F"),
    HoldingsSubject("third-point", "Third Point", "institution", 1040273,
                    "Third Point LLC", "Third Point LLC 13F"),
    HoldingsSubject("greenlight", "Greenlight Capital", "institution", 1489933,
                    "DME Capital Management, LP", "DME Capital Management LP 13F"),
    HoldingsSubject("baupost", "Baupost Group", "institution", 1061768,
                    "BAUPOST GROUP LLC/MA", "Baupost Group LLC 13F"),
    HoldingsSubject("duquesne", "Duquesne Family Office", "institution", 1536411,
                    "Duquesne Family Office LLC", "Duquesne Family Office LLC 13F"),
    HoldingsSubject("point72", "Point72", "institution", 1603466,
                    "Point72 Asset Management, L.P.", "Point72 Asset Management LP 13F"),
    HoldingsSubject("viking-global", "Viking Global", "institution", 1103804,
                    "VIKING GLOBAL INVESTORS LP", "Viking Global Investors LP 13F"),
    HoldingsSubject("elliott", "Elliott Investment Management", "institution", 1791786,
                    "Elliott Investment Management L.P.", "Elliott Investment Management LP 13F"),
    HoldingsSubject("himalaya", "Himalaya Capital", "institution", 1709323,
                    "Himalaya Capital Management LLC", "Himalaya Capital Management LLC 13F"),
    HoldingsSubject("soros", "Soros Fund Management", "institution", 1029160,
                    "SOROS FUND MANAGEMENT LLC", "Soros Fund Management LLC 13F"),
    HoldingsSubject("de-shaw", "D. E. Shaw", "institution", 1009207,
                    "D. E. Shaw & Co., Inc.", "D. E. Shaw & Co., Inc. 13F"),
    HoldingsSubject("millennium", "Millennium Management", "institution", 1273087,
                    "MILLENNIUM MANAGEMENT LLC", "Millennium Management LLC 13F"),
    HoldingsSubject("two-sigma", "Two Sigma", "institution", 1179392,
                    "TWO SIGMA INVESTMENTS, LP", "Two Sigma Investments LP 13F"),
    HoldingsSubject("aqr", "AQR Capital Management", "institution", 1167557,
                    "AQR CAPITAL MANAGEMENT LLC", "AQR Capital Management LLC 13F"),
    HoldingsSubject("lone-pine", "Lone Pine Capital", "institution", 1061165,
                    "LONE PINE CAPITAL LLC", "Lone Pine Capital LLC 13F"),
    HoldingsSubject("farallon", "Farallon Capital Management", "institution", 909661,
                    "FARALLON CAPITAL MANAGEMENT, L.L.C.", "Farallon Capital Management LLC 13F"),
    HoldingsSubject("trian", "Trian Fund Management", "institution", 1345471,
                    "TRIAN FUND MANAGEMENT, L.P.", "Trian Fund Management LP 13F"),
    HoldingsSubject("glenview", "Glenview Capital", "institution", 1138995,
                    "GLENVIEW CAPITAL MANAGEMENT, LLC", "Glenview Capital Management LLC 13F"),
    HoldingsSubject("maverick", "Maverick Capital", "institution", 934639,
                    "MAVERICK CAPITAL LTD", "Maverick Capital Ltd 13F"),
    HoldingsSubject("balyasny", "Balyasny Asset Management", "institution", 1218710,
                    "BALYASNY ASSET MANAGEMENT L.P.", "Balyasny Asset Management LP 13F"),
    HoldingsSubject("marshall-wace", "Marshall Wace", "institution", 1318757,
                    "MARSHALL WACE, LLP", "Marshall Wace LLP 13F"),
    HoldingsSubject("select-equity", "Select Equity Group", "institution", 1592643,
                    "Select Equity Group, L.P.", "Select Equity Group LP 13F"),
    HoldingsSubject("capital-research-global", "Capital Research Global Investors", "institution", 1422848,
                    "Capital Research Global Investors", "Capital Research Global Investors 13F"),
    HoldingsSubject("primecap", "PRIMECAP Management", "institution", 763212,
                    "PRIMECAP MANAGEMENT CO/CA/", "PRIMECAP Management Co. 13F"),
    HoldingsSubject("dodge-cox", "Dodge & Cox", "institution", 200217,
                    "DODGE & COX", "Dodge & Cox 13F"),
)
