import type { SvInvestor, SvSource } from "./types";

export const FALLBACK_NARRATIVES = [
  { key: "semis", zh: "半导体", en: "Semiconductors", weight: 34 },
  { key: "ai_infra", zh: "AI 基础设施", en: "AI infrastructure", weight: 24 },
  { key: "software", zh: "软件与云", en: "Software & cloud", weight: 16 },
  { key: "crypto", zh: "加密相关", en: "Crypto-linked", weight: 10 },
];

export const NARRATIVE_LABELS: Record<string, { zh: string; en: string }> = {
  semis: { zh: "半导体", en: "Semiconductors" },
  ai_infra: { zh: "AI 基础设施", en: "AI infrastructure" },
  software: { zh: "软件与云", en: "Software & cloud" },
  media: { zh: "媒体娱乐", en: "Media & entertainment" },
  ev: { zh: "电动车", en: "EV" },
  crypto: { zh: "加密相关", en: "Crypto-linked" },
  consumer: { zh: "消费与零售", en: "Consumer" },
  fintech: { zh: "金融科技", en: "Fintech" },
};

export const TICKER_NARRATIVE: Record<string, string> = {
  NVDA: "semis",
  MU: "semis",
  AMD: "semis",
  INTC: "semis",
  AVGO: "semis",
  AMAT: "semis",
  TSM: "semis",
  PLTR: "ai_infra",
  SMCI: "ai_infra",
  DELL: "ai_infra",
  MSFT: "software",
  CRM: "software",
  NOW: "software",
  NFLX: "media",
  DIS: "media",
  TSLA: "ev",
  RIVN: "ev",
  COIN: "crypto",
  MSTR: "crypto",
  SQ: "fintech",
  HOOD: "fintech",
  AMZN: "consumer",
  BABA: "consumer",
};

export function sourceUrl(source: SvSource, handle: string, id: string) {
  if (source === "x") return `https://x.com/${handle.replace(/^@/, "")}`;
  return `https://www.youtube.com/channel/${id}`;
}

export const INVESTORS: SvInvestor[] = [
  {
    id: "x:sixsigma",
    source: "x",
    name: "@SixSigmaCapital",
    handle: "SixSigmaCapital",
    language: "en",
    sv: 128,
    confidence: "high",
    nEff: 118,
    settledCalls: 164,
    activeDays: 73,
    coveredTickers: 34,
    topTickers: ["MU", "NVDA", "INTC", "AVGO"],
    topNarratives: ["semis", "ai_infra"],
    platformScores: { x: 130 },
    horizonScores: { "1D": 113, "5D": 134, "20D": 126, "60D": 111 },
    narrativeScores: { semis: 141, ai_infra: 132, software: 108 },
    tickerScores: { MU: 146, NVDA: 133, INTC: 128, AVGO: 121, PLTR: 118 },
    rationaleZh: "半导体短线与波段 call 持续跑赢同标的基准，样本覆盖较宽。",
    rationaleEn: "Consistently beats ticker baselines on semiconductor short-term and swing calls with broad coverage.",
  },
  {
    id: "x:chanos",
    source: "x",
    name: "@RealJimChanos",
    handle: "RealJimChanos",
    language: "en",
    sv: 123,
    confidence: "high",
    nEff: 96,
    settledCalls: 142,
    activeDays: 61,
    coveredTickers: 22,
    topTickers: ["TSLA", "COIN", "RIVN", "NFLX"],
    topNarratives: ["ev", "crypto", "media"],
    platformScores: { x: 124 },
    horizonScores: { "1D": 106, "5D": 118, "20D": 130, "60D": 126 },
    narrativeScores: { ev: 136, crypto: 128, media: 119, consumer: 103 },
    tickerScores: { TSLA: 139, COIN: 129, RIVN: 126, NFLX: 116 },
    rationaleZh: "空头与反共识观点兑现率高，尤其在高估值与事件驱动标的上稳定。",
    rationaleEn: "Bearish and contrarian calls score well, especially on high-valuation and event-driven names.",
  },
  {
    id: "yt:rule1",
    source: "youtube",
    name: "Rule #1 Investing",
    handle: "@rule1investing",
    language: "en",
    sv: 121,
    confidence: "medium",
    nEff: 58,
    settledCalls: 83,
    activeDays: 44,
    coveredTickers: 18,
    topTickers: ["NFLX", "AMZN", "BABA", "DIS"],
    topNarratives: ["consumer", "media"],
    platformScores: { youtube: 122 },
    horizonScores: { "1D": 98, "5D": 106, "20D": 124, "60D": 132 },
    narrativeScores: { media: 134, consumer: 126, software: 112 },
    tickerScores: { NFLX: 138, AMZN: 124, BABA: 119, DIS: 116 },
    rationaleZh: "中期价值修复类观点更强，目标价与估值框架较完整。",
    rationaleEn: "Stronger on medium-term value-reversion calls with explicit targets and valuation frameworks.",
  },
  {
    id: "x:bluth",
    source: "x",
    name: "@BluthCapital",
    handle: "BluthCapital",
    language: "en",
    sv: 119,
    confidence: "high",
    nEff: 88,
    settledCalls: 126,
    activeDays: 69,
    coveredTickers: 29,
    topTickers: ["MU", "PLTR", "CRM", "COIN"],
    topNarratives: ["semis", "software", "crypto"],
    platformScores: { x: 120 },
    horizonScores: { "1D": 111, "5D": 121, "20D": 122, "60D": 104 },
    narrativeScores: { semis: 125, software: 122, crypto: 117 },
    tickerScores: { MU: 128, PLTR: 124, CRM: 121, COIN: 116 },
    rationaleZh: "覆盖面广，短期和短中期表现均衡，适合做跨赛道参考。",
    rationaleEn: "Broad coverage with balanced short-term and swing performance across multiple narratives.",
  },
  {
    id: "yt:patient",
    source: "youtube",
    name: "The Patient Investor",
    handle: "@patientinvestor",
    language: "en",
    sv: 116,
    confidence: "medium",
    nEff: 47,
    settledCalls: 68,
    activeDays: 38,
    coveredTickers: 15,
    topTickers: ["NVDA", "MSFT", "NFLX", "AMZN"],
    topNarratives: ["ai_infra", "software", "media"],
    platformScores: { youtube: 117 },
    horizonScores: { "1D": 92, "5D": 101, "20D": 119, "60D": 128 },
    narrativeScores: { ai_infra: 124, software: 120, media: 116 },
    tickerScores: { NVDA: 125, MSFT: 119, NFLX: 112, AMZN: 111 },
    rationaleZh: "长视频中的中期 thesis 更有参考性，短线跟单价值较弱。",
    rationaleEn: "Medium-term theses from long-form videos are more useful than short-term timing.",
  },
  {
    id: "x:limitless",
    source: "x",
    name: "@Limitlesss1",
    handle: "Limitlesss1",
    language: "en",
    sv: 114,
    confidence: "medium",
    nEff: 62,
    settledCalls: 91,
    activeDays: 55,
    coveredTickers: 26,
    topTickers: ["NVDA", "AMD", "PLTR", "SMCI"],
    topNarratives: ["ai_infra", "semis"],
    platformScores: { x: 115 },
    horizonScores: { "1D": 117, "5D": 119, "20D": 110, "60D": 97 },
    narrativeScores: { ai_infra: 124, semis: 118, software: 104 },
    tickerScores: { NVDA: 122, AMD: 118, PLTR: 120, SMCI: 116 },
    rationaleZh: "AI 硬件与高 beta 科技股短线节奏较好，但中期样本仍不足。",
    rationaleEn: "Good short-term timing on AI hardware and high-beta tech, with thinner medium-term evidence.",
  },
  {
    id: "yt:futurum",
    source: "youtube",
    name: "Futurum Equities",
    handle: "@futurumequities",
    language: "en",
    sv: 112,
    confidence: "medium",
    nEff: 41,
    settledCalls: 59,
    activeDays: 35,
    coveredTickers: 14,
    topTickers: ["CRM", "NOW", "MSFT", "PLTR"],
    topNarratives: ["software", "ai_infra"],
    platformScores: { youtube: 113 },
    horizonScores: { "1D": 91, "5D": 99, "20D": 118, "60D": 120 },
    narrativeScores: { software: 127, ai_infra: 116, semis: 101 },
    tickerScores: { CRM: 128, NOW: 124, MSFT: 116, PLTR: 110 },
    rationaleZh: "软件和 AI 应用层中期观点更强，短线不是主要优势。",
    rationaleEn: "Stronger on medium-term software and AI application calls than short-term timing.",
  },
  {
    id: "x:coles",
    source: "x",
    name: "@ColesTrades",
    handle: "ColesTrades",
    language: "en",
    sv: 109,
    confidence: "medium",
    nEff: 50,
    settledCalls: 86,
    activeDays: 48,
    coveredTickers: 17,
    topTickers: ["HOOD", "SQ", "COIN", "MSTR"],
    topNarratives: ["fintech", "crypto"],
    platformScores: { x: 110 },
    horizonScores: { "1D": 116, "5D": 113, "20D": 104, "60D": 93 },
    narrativeScores: { fintech: 121, crypto: 117, software: 96 },
    tickerScores: { HOOD: 123, SQ: 115, COIN: 112, MSTR: 110 },
    rationaleZh: "金融科技和加密相关标的短线 call 较强，但长周期可信度较低。",
    rationaleEn: "Short-term calls on fintech and crypto-linked names are stronger than longer horizons.",
  },
  {
    id: "yt:schwab",
    source: "youtube",
    name: "Schwab Network",
    handle: "@schwabnetwork",
    language: "en",
    sv: 104,
    confidence: "medium",
    nEff: 64,
    settledCalls: 105,
    activeDays: 52,
    coveredTickers: 31,
    topTickers: ["AAPL", "MSFT", "AMZN", "TSLA"],
    topNarratives: ["software", "consumer", "ev"],
    platformScores: { youtube: 105 },
    horizonScores: { "1D": 101, "5D": 103, "20D": 106, "60D": 107 },
    narrativeScores: { software: 109, consumer: 105, ev: 99 },
    tickerScores: { AAPL: 108, MSFT: 109, AMZN: 105, TSLA: 98 },
    rationaleZh: "覆盖面广但观点偏市场平均，适合作为背景声音。",
    rationaleEn: "Broad coverage but close to market median, useful as background context.",
  },
  {
    id: "x:memewhale",
    source: "x",
    name: "@unusual_whales",
    handle: "unusual_whales",
    language: "en",
    sv: 98,
    confidence: "high",
    nEff: 142,
    settledCalls: 238,
    activeDays: 82,
    coveredTickers: 39,
    topTickers: ["GME", "AMC", "TSLA", "COIN"],
    topNarratives: ["crypto", "ev"],
    platformScores: { x: 99 },
    horizonScores: { "1D": 101, "5D": 97, "20D": 96, "60D": 94 },
    narrativeScores: { crypto: 103, ev: 96, semis: 92 },
    tickerScores: { GME: 106, AMC: 104, TSLA: 94, COIN: 101 },
    rationaleZh: "高覆盖高互动，但方向性准确度接近或低于 Prismo 中位数。",
    rationaleEn: "High reach and broad coverage, but directional accuracy is near or below the Prismo median.",
  },
];

for (const investor of INVESTORS) {
  investor.url = sourceUrl(investor.source, investor.handle, investor.id.replace(/^yt:/, ""));
  if (investor.source === "x") investor.avatar = `https://unavatar.io/twitter/${investor.handle}`;
}
